UPPER_ANTERIOR_SEGMENT = """
Get the following points using Upper Arch Segment
Label them as follows:
    >> Left 1 - mesial (L1M)
    >> Left 1 - mid (L1Mid)
    >> Left 1 - distal (L1D)
    >> Left 2 - mesial (L2M)
    >> Left 2 - mid (L2Mid)
    >> Left 2 - distal (L2D)
    >> Left 3 - mesial (L3M)
    >> Left 3 - mid (L3Mid)
    >> Left 4 - buccal tip (L4BT)
    >> Left 4 - palatal tip (L4PT)
    >> Left 5 - buccal tip (L5BT)
    >> Left 5 - palatal tip (L5PT)
    >> Left 6 - mesial buccal (L6MB)
    >> Left 6 - distal buccal (L6DB)
    >> Left 6 - mesial palatal (L6MP)
    >> Left 6 - distal palatal (L6DP)
    >> Left 7 - mesial buccal (L7MB)
    >> Left 7 - distal buccal (L7DB)
    >> Left 7 - mesial palatal (L7MP)
    >> Left 7 - distal palatal (L7DP)
    ---------------------------------
    >> Right 1 - mesial (R1M)
    >> Right 1 - mid (R1Mid)
    >> Right 1 - distal (R1D)
    >> Right 2 - mesial (R2M)
    >> Right 2 - mid (R2Mid)
    >> Right 2 - distal (R2D)
    >> Right 3 - mesial (R3M)
    >> Right 3 - mid (R3Mid)
    >> Right 4 - buccal tip (R4BT)
    >> Right 4 - palatal tip (R4PT)
    >> Right 5 - buccal tip (R5BT)
    >> Right 5 - palatal tip (R5PT)
    >> Right 6 - mesial buccal (R6MB)
    >> Right 6 - distal buccal (R6DB)
    >> Right 6 - mesial palatal (R6MP)
    >> Right 6 - distal palatal (R6DP)
    >> Right 7 - mesial buccal (R7MB)
    >> Right 7 - distal buccal (R7DB)
    >> Right 7 - mesial palatal (R7MP)
    >> Right 7 - distal palatal (R7DP)
"""

LOWER_ANTERIOR_SEGMENT = '''
Get the following points using Lower Arch Segment
Label them as follows:
    >> Left 1 - mesial (L1M)
    >> Left 1 - mid (L1Mid)
    >> Left 1 - distal (L1D)
    >> Left 2 - mesial (L2M)
    >> Left 2 - mid (L2Mid)
    >> Left 2 - distal (L2D)
    >> Left 3 - mesial (L3M)
    >> Left 3 - mid (L3Mid)
    >> Left 4 - buccal tip (L4BT)
    >> Left 4 - palatal tip (L4PT)
    >> Left 5 - buccal tip (L5BT)
    >> Left 5 - palatal tip (L5PT)
    >> Left 6 - mesial (L6M)
    >> Left 6 - mesial buccal (L6MB)
    >> Left 6 - distal buccal (L6DB)
    >> Left 6 - mesial palatal (L6MP)
    >> Left 6 - distal palatal (L6DP)
    >> Left 6 - groove buccal (L6GB) 
    >> Left 6 - groove palatal (L6GP)
    >> Left 7 - mesial (L7M)
    >> Left 7 - mesial buccal (L7MB)
    >> Left 7 - distal buccal (L7DB)
    >> Left 7 - mesial palatal (L7MP)
    >> Left 7 - distal palatal (L7DP)
    >> Left 7 - groove buccal (L7GB) 
    >> Left 7 - groove palatal (L7GP)
    ---------------------------------
    >> Right 1 - mesial (R1M)
    >> Right 1 - mid (R1Mid)
    >> Right 1 - distal (R1D)
    >> Right 2 - mesial (R2M)
    >> Right 2 - mid (R2Mid)
    >> Right 2 - distal (R2D)
    >> Right 3 - mesial (R3M)
    >> Right 3 - mid (R3Mid)
    >> Right 4 - buccal tip (R4BT)
    >> Right 4 - palatal tip (R4PT)
    >> Right 5 - buccal tip (R5BT)
    >> Right 5 - palatal tip (R5PT)
    >> Right 6 - mesial (R6M)
    >> Right 6 - mesial buccal (R6MB)
    >> Right 6 - distal buccal (R6DB)
    >> Right 6 - mesial palatal (R6MP)
    >> Right 6 - distal palatal (R6DP)
    >> Right 6 - groove buccal (R6GB)
    >> Right 6 - groove palatal (R6GP)
    >> Right 7 - mesial (R7M)
    >> Right 7 - mesial buccal (R7MB)
    >> Right 7 - distal buccal (R7DB)
    >> Right 7 - mesial palatal (R7MP)
    >> Right 7 - distal palatal (R7DP)
    >> Right 7 - groove buccal (R7GB)
    >> Right 7 - groove palatal (R7GP)
    >> Lower point of Right 1 (R1Lower)

'''

BUCCAL_SEGMENT = '''
Get the following points using Buccal Segment
Label them as follows:
    >> Contact point of the upper Right 1 (OJ_UCP)
    >> Contact point of the lower Right 1 (OJ_LCP)
    >> Covering point of the lower Right 1 (LCover)
'''
